<a href="https://colab.research.google.com/github/othoni-hub/ECG2/blob/main/Ch04_ReductionMatrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CPGE-ECG2** 




## **Ch4 - Notebook : Réductions des Matrices**

<img src="https://drive.google.com/uc?id=12Wo3LubGGT4qOvYFAuLP4CyCuwjKNVuk" width="230" height="150" align = "right"/>




**O.Thöni - Lycée Saint-Charles Sainte Croix - LE MANS**

## **Utilisation du module *NumPy.LinAlg***

(procédé conforme au programme officiel d'ECG2)


In [1]:
import numpy as np
import numpy.linalg as al

In [2]:
A = np.array([[-2,-2, 1 ], [-2, 1, -2], [1, -2, -2]])
A

array([[-2, -2,  1],
       [-2,  1, -2],
       [ 1, -2, -2]])

La fonction qui permet de diagonaliser une matrice est **"*alg*"**, 

elle renvoie deux tableaux *NumPy*, D, tableau-ligne des valeurs propres de A, et V, matrice des vecteurs propres.

---

In [3]:
D, V = al.eig(A)

---

In [4]:
D

array([-3.,  3., -3.])

Si l'on veut la transformer en matrice diagonale, on utilise la fonction diag de *NumPy*

In [5]:
D = np.diag(D)
D

array([[-3.,  0.,  0.],
       [ 0.,  3.,  0.],
       [ 0.,  0., -3.]])

In [6]:
V

array([[-0.91287093, -0.40824829, -0.12309149],
       [-0.36514837,  0.81649658,  0.39389277],
       [ 0.18257419, -0.40824829,  0.91087703]])

La 1<sup>ère</sup> colonne est censée être un vecteur propre associé à la 1<sup>ère</sup> valeur propre, voyons cela...

**Attention :** si l'on récupère la 1<sup>ère</sup> colonne, sans précaution, on obtiendra un *array* à une ligne, qu'il ne sera pas possible de transposer pour en faire un vecteur-colonne.

Pour parvenir à nos fins, on définit notre vecteur avec doubles-*brackets* pour qu'il soit considéré comme bidimensionnel. On pourra alors le transposer !

In [7]:
V1 = np.array([[V[i][0] for i in range(len(D))]])
V1

array([[-0.91287093, -0.36514837,  0.18257419]])

In [8]:
V1 = np.transpose(V1)
V1

array([[-0.91287093],
       [-0.36514837],
       [ 0.18257419]])

Vérifions maintenant si V1 est bien un vecteur propre associé à la 1<sup>ère</sup> valeur propre de A...

In [9]:
A @ V1 # vrai produit matriciel. Autre méthode : A.dot(V1)

array([[ 2.73861279],
       [ 1.09544512],
       [-0.54772256]])

In [10]:
A.dot(V1) - D[0][0]*V1

array([[ 0.00000000e+00],
       [ 0.00000000e+00],
       [-1.11022302e-16]])

... valeurs suffisamment petites pour être considérées comme nulles...

Par contre, on n'a pas testé "A.dot(V1) == D[0][0] \* V1" qui aurait répondu 'False' : **ne pas comparer des flottants**, du fait de leur implémentation en Python, on a des erreurs d'arrondis rendant les comparaisons impossibles (la preuve, la différence ci-dessus ne done pas pile 0...)

In [11]:
A.dot(V1) == D[0][0]*V1

array([[ True],
       [ True],
       [False]])

## **Reconstruction plus algébrique**

*(Non exigible selon le programme officiel)*

Il existe un module Python assez impressionnant permettant le calcul symbolique. Il se nomme ***SymPy***.

Nous le remettrons à l'oeuvre quand nous aborderons la résolution numérique d'équations et de systèmes différentiels.

In [12]:
import sympy as sp

In [13]:
x, y = sp.symbols('x y')

A=sp.Matrix([[1,3],[2,-4]])
A

Matrix([
[1,  3],
[2, -4]])

In [14]:
X=sp.Matrix([[x],[y]])
X

Matrix([
[x],
[y]])

Il paraît que -5 est valeur propre de A...

On cherche à résoudre $A.X=-5X$

$\left\{\begin{matrix} x + 3y = -5x\\2x -  4y = -5y\end{matrix}\right.\Leftrightarrow\left\{\begin{matrix}6x + 3y = 0\\2x +  y = 0\end{matrix}\right.
  \Leftrightarrow
 2x +  y = 0\Leftrightarrow
 x= \frac{-y}{2}$

In [15]:
sp.pprint(sp.solve(-5*X-A*X)) # pprint : "pretty print"

⎧   -y ⎫
⎨x: ───⎬
⎩    2 ⎭


*SymPy* permet d'écrire $Ker(A+5I)$ avec la méthode *nullspace()*

In [16]:
sp.pprint((-5*sp.eye(2)-A).nullspace())

⎡⎡-1/2⎤⎤
⎢⎢    ⎥⎥
⎣⎣ 1  ⎦⎦


On peut obtenir le polynôme caractéristique de A (le polynôme que l'on obtient en bas à droite dans la trigonalisée de $A-\lambda . I$, celi dont on cherche les racines...)

In [17]:
P=sp.Matrix.charpoly(A)
sp.pprint(P)

PurePoly(lambda**2 + 3*lambda - 10, lambda, domain='ZZ')


In [18]:
z=sp.factor_list(P)
sp.pprint(z)

(1, [(PurePoly(lambda - 2, lambda, domain='ZZ'), 1), (PurePoly(lambda + 5, lam
bda, domain='ZZ'), 1)])


In [19]:
P = sp.poly(P)
P

Poly(lambda**2 + 3*lambda - 10, lambda, domain='ZZ')

In [20]:
#P = x**2+3*x-10
racines=sp.solve(P, extension  = sp.sqrt(2)) ## l'extension permet de travailler si besoin avec des irrationnels, sion, domain = ZZ)
racines

[-5, 2]

**Valeurs propres et vecteurs propres d'une matrice**

In [21]:
M = sp.Matrix([[3, -2,  4, -2],
              [5,  3, -3, -2],
              [5, -2,  2, -2],
              [5, -2, -3,  3]])
sp.pprint(M.eigenvals())


{-2: 1, 3: 1, 5: 2}


La méthode *.eingenvals()* renvoie un dictionnaire ayant pour clés les valeurs propres de la Matrice *Sympy*, et pour valeurs leur ordre de multiplicité.

La méthode *.eingenvects()* renvoie une liste de liste, contenant chacune chaque valeur propre, son ordre de multiplicité, et une base de vecteurs propres.

In [22]:
sp.pprint(M.eigenvects())

⎡⎛       ⎡⎡0⎤⎤⎞  ⎛      ⎡⎡1⎤⎤⎞  ⎛      ⎡⎡1⎤  ⎡0 ⎤⎤⎞⎤
⎢⎜       ⎢⎢ ⎥⎥⎟  ⎜      ⎢⎢ ⎥⎥⎟  ⎜      ⎢⎢ ⎥  ⎢  ⎥⎥⎟⎥
⎢⎜       ⎢⎢1⎥⎥⎟  ⎜      ⎢⎢1⎥⎥⎟  ⎜      ⎢⎢1⎥  ⎢-1⎥⎥⎟⎥
⎢⎜-2, 1, ⎢⎢ ⎥⎥⎟, ⎜3, 1, ⎢⎢ ⎥⎥⎟, ⎜5, 2, ⎢⎢ ⎥, ⎢  ⎥⎥⎟⎥
⎢⎜       ⎢⎢1⎥⎥⎟  ⎜      ⎢⎢1⎥⎥⎟  ⎜      ⎢⎢1⎥  ⎢0 ⎥⎥⎟⎥
⎢⎜       ⎢⎢ ⎥⎥⎟  ⎜      ⎢⎢ ⎥⎥⎟  ⎜      ⎢⎢ ⎥  ⎢  ⎥⎥⎟⎥
⎣⎝       ⎣⎣1⎦⎦⎠  ⎝      ⎣⎣1⎦⎦⎠  ⎝      ⎣⎣0⎦  ⎣1 ⎦⎦⎠⎦
